### ISSUE TITLE
ERA5T tracking

### ISSUE THREAD

**Issue by JimCircadian** [environmental-forecasting/download-toolbox#20]
Preliminary data can come out of ERA5 as partially discussed here: #14 as well as in other places. 

We need to do the following: 

* [ ] Record the ingress of ERA5T dates
* [ ] Provide a CLI option to look at and overwrite those dates (rather than assuming) - this requires querying dates in the list and then, if ERA5 data comes out rather than ERA5T, overwriting the data in the dataset
* [ ] Remove the dates from the list **but also record the provenance of the overwrite: how are we distinguishing pre and post preliminary data download?** This might tie into a versioning strategy for the datasets so downstream knows something changed. 
* [ ] Raise any particular issues for versioning and retention of state change information
